#!/bin/bash

# Correr con `sbatch /ruta/a/este/script

#SBATCH --job-name="m_01_6"
#SBATCH --nodes=1                    # Use one node
#SBATCH --ntasks=1                   # Run a single task
#SBATCH --cpus-per-task=8            # Number of CPU cores per task
#SBATCH --workdir=/home/lmoffatt/macro-dr/Data
#SBATCH --error="m10_6-%j.err"
#SBATCH --output="m10_6-%j.out"
#SBATCH --account=freeriders
#SBATCH --partition=freeriders
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lmoffatt@gmail.com

echo "trabajo \"${SLURM_JOB_NAME}\""
echo "    id: ${SLURM_JOB_ID}"
echo "    partición: ${SLURM_JOB_PARTITION}"
echo "    nodos: ${SLURM_JOB_NODELIST}"
echo
date +"inicio %F - %T"

echo "
--------------------------------------------------------------------------------
"

# INICIO VARIABLES IMPORTANTES
#
# NO TOCAR. No se aceptan reclamos en caso de modificar estas líneas. Deberán
# incluirlas siempre, hasta próximo aviso.
#
[ -r /etc/profile.d/odin-users.sh ] && . /etc/profile.d/odin-users.sh
#
# FIN VARIABLES IMPORTANTES

# El path al programa es `/home/USUARIO/ejemplos/programa-openmp`. Como más
# arriba seteamos el directorio de trabajo a `/home/USUARIO/ejemplos`, el
# programa se encuentra en el directorio de trabajo, por lo que basta poner
# `./programa-openmp`.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lmoffatt/gcc-8.2/lib64/
export OMP_NUM_THREADS=8
srun /home/lmoffatt/macro-dr/parallel/macro-dr /home/lmoffatt/macro-dr/macro-dr/cecar/scripts/m1_EvidenceDProb02_MacroDMR.txt


echo "
--------------------------------------------------------------------------------
"

date +"fin %F - %T"
